project:
  type: website
  output-dir: _site

  preview:
      port: 8086
      browser: true

execute:
  freeze: auto
  warning: false
  message: false

editor: visual

website:
  title: "GenAI Wiki"
  favicon: ""
  site-url: https://saddlerto.github.io/genai-wiki-quarto
  description: "A wiki about generative AI."
  twitter-card:
    creator: "@tosaddler"
    site: "@tosaddler"
  open-graph: true
  repo-url: https://github.com/saddlerto/genai-wiki-quarto
  issue-url: https://github.com/saddlerto/genai-wiki-quarto/issues
  repo-branch: hugo
  repo-actions:
    - edit
    - source
    - issue

  navbar:
    # logo: "/imgs/logo.png"
    logo-alt: ""
    logo-href: "https://saddlerto.github.io/genai-wiki-quarto"
    title: "GenAI Wiki"
    right:
      - models/index.qmd
      - tools/index.qmd
      - resources/index.qmd
      - entities/index.qmd
      - metrics/index.qmd
      - data/index.qmd
      - glossary/index.qmd

  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v<?quarto.version?> | Hosted by [{{< iconify simple-icons github >}}](https://pages.github.com/)"
    right: "© 2024 saddlerto, Some Rights Reserved | [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode.en)<br>"

format:
  html:
    lang: en
    author-meta: Trey Saddler
    theme: cerulean
    css: 
      - styles.css
    # highlight-style: dracula

    toc: true
    toc-title: Table of Contents
    toc-location: right

    link-external-newwindow: true

    code-line-numbers: true
    code-fold: true
    code-annotations: true
    code-overflow: wrap
    code-copy: hover

    smooth-scroll: true

    fig-align: center
    fig-responsive: true

    anchor-sections: true
    callout-appearance: simple
    email-obfuscation: javascript
    
resources:
  - "assets/*"

filters:
  - quarto-version.lua
  - shinylive
