project:
  type: website
  output-dir: _site

  preview:
      port: 8086
      browser: true

execute:
  freeze: auto
  warning: false
  message: false

editor: visual

website:
  title: "GenAI Wiki"
  favicon: ""
  site-url: https://saddlerto.github.io/genai-wiki-quarto
  description: "A wiki about generative AI."
  twitter-card:
    creator: "@tosaddler"
    site: "@tosaddler"
  open-graph: true
  repo-url: https://github.com/saddlerto/genai-wiki-quarto
  issue-url: https://github.com/saddlerto/genai-wiki-quarto/issues
  repo-branch: hugo
  repo-actions:
    - edit
    - source
    - issue

  navbar:
    # logo: "/imgs/logo.png"
    logo-alt: ""
    logo-href: "https://saddlerto.github.io/genai-wiki-quarto"
    title: false
    right:
      - models/index.qmd
      - text: "{{< iconify bi:tools >}} Tools"
        href: /tools/
      - text: Resources
        href: /resources/
      - text: Entities
        href: /entities/
      - text: Metrics
        href: /metrics/
      - text: Data
        href: /data/
      - text: Glossary
        href: /glossary/

  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v<?quarto.version?> | Hosted by [{{< iconify simple-icons github >}}](https://pages.github.com/)"
    right: "© 2024 saddlerto, Some Rights Reserved | [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode.en)<br>"

format:
  html:
    lang: en
    author-meta: Trey Saddler
    theme: 
      light: flatly
      dark: darkly
    css: 
      - styles.css
    include-in-header: "csp.html"
    highlight-style: dracula

    toc: true
    toc-title: Table of Contents
    toc-location: right

    link-external-newwindow: true

    code-line-numbers: true
    code-fold: true
    code-annotations: true
    code-overflow: wrap
    code-copy: hover

    smooth-scroll: true

    fig-align: center
    fig-responsive: true

    anchor-sections: true
    callout-appearance: simple
    email-obfuscation: javascript
    
filters:
  - quarto-version.lua
